export const clubsDatas = [
    {
        id: "1",
        name: "Shoko Mohali (Bestech Square Mall)",
        location: "Unit No. 028, 5th Floor, Bestech Square Mall, Sector 66, Mohali – Punjab 160062",
        timing: "7:00 PM – 3:00 AM (All Days)",
        avgCost: "₹1,800 – ₹2,000 (approx.)",
        highlights: "Premium nightclub with luxurious interiors, dance floor, live DJ, cocktails & valet parking. Located inside Mohali’s most popular mall.",
        notes: "Youth-favourite weekend spot; known for high-energy crowd and late-night events.",
    },
        {
        id: "2",
        name: "La Vella Club Chandigarh",
        location: "Behind Water Works Colony, SCO 55, Sector 26, Chandigarh",
        timing: "Till 3:00 AM",
        avgCost: "₹1,500 – ₹2,000",
        highlights: "High-vibe club in Sector 26 with live DJs, cocktails, premium bar, and large dance floor. Popular for nightlife & parties.",
        notes: "One of Chandigarh’s most active weekend clubs; check event calendar for theme nights.",
    },    
     {
        id: "3",
        name: "Diroma Estiatorio Bar & Kitchen",
        location: "SCO 69-70, Hi5 Mall, Sector 5, Panchkula",
        timing: "12:00 PM – 11:30 PM (weekdays) ; up to 1:00 AM (weekends)",
        avgCost: "₹1,400 (approx.)",
        highlights: "Rooftop bar + restaurant with Roman-inspired ambience, indoor/outdoor seating, cocktails & continental food.",
        notes: "Great for dinner + lounge experience; attracts mixed crowd; weekend DJ nights.",
    },
       {
        id: "4",
        name: "Da Bodega (Bar & Kitchen)",
        location: "SCO 47, Sector 5, Panchkula (near Hotel Shiraaz 2)",
        timing: "11:00 AM – 3:00 AM",
        avgCost: "₹1,800 – ₹2,000",
        highlights: "Multi-cuisine lounge & bar; indoor + outdoor seating; live DJ; great food + cocktails.",
        notes: "Combines fine dining with nightlife; popular for celebrations.",
    },
         {
        id: "5",
        name: "Barrio by Bodega",
        location: "SCO 44, Backside Sector 26, Chandigarh",
        timing: "12:00 PM – 3:00 AM",
        avgCost: "₹1,000 – ₹1,500",
        highlights: "Stylish bar + lounge; live music, cocktails, dance floor, open-air area.",
        notes: "Great for dinner + lounge experience; attracts mixed crowd; weekend DJ nights.",
    },
             {
        id: "6",
        name: "Playboy Club Chandigarh",
        location: "3rd Floor, City Emporium Mall, Industrial Area Phase I, Chandigarh",
        timing: "8:00 PM – 4:00 AM",
        avgCost: "₹2,000 – ₹2,500",
        highlights: "International franchise nightclub; luxury interiors, LED lighting, VIP tables, professional DJs.",
        notes: "Premium crowd; entry via guest list or paid table booking; hosts celebrity events.",
    },
               {
        id: "7",
        name: "Dimokaa – The Premium Night Club",
        location: "Ground Floor, SCO 69-70, Near Hi5 Mall, Sector 5, Panchkula",
        timing: "Not listed (usually 7 PM – 3 AM)",
        avgCost: "Not listed (approx. ₹1,800)",
        highlights: "Newly opened premium nightclub; modern interiors, full bar, dance floor, and high-energy music.",
        notes: "Located near Diroma; growing popularity; details like dress code & cover charges need confirmation.",
    },
               {
        id: "8",
        name: "Barrio by Bodega",
        location: "SCO 44, Backside Sector 26, Chandigarh",
        timing: "12:00 PM – 3:00 AM",
        avgCost: "₹1,000 – ₹1,500",
        highlights: "Stylish bar + lounge; live music, cocktails, dance floor, open-air area.",
        notes: "Youth-friendly; often hosts themed or DJ nights; casual dress code.",
    },
             {
        id: "9",
        name: "Playboy Club Chandigarh",
        location: "3rd Floor, City Emporium Mall, Industrial Area Phase I, Chandigarh",
        timing: "8:00 PM – 4:00 AM",
        avgCost: "₹2,000 – ₹2,500",
        highlights: "International franchise nightclub; luxury interiors, LED lighting, VIP tables, professional DJs.",
        notes: "Premium crowd; entry via guest list or paid table booking; hosts celebrity events.",
    },
                   {
        id: "10",
        name: "Dimokaa – The Premium Night Club",
        location: "Ground Floor, SCO 69-70, Near Hi5 Mall, Sector 5, Panchkula",
        timing: "Not listed (usually 7 PM – 3 AM)",
        avgCost: "Not listed (approx. ₹1,800)",
        highlights: "Newly opened premium nightclub; modern interiors, full bar, dance floor, and high-energy music.",
        notes: "Located near Diroma; growing popularity; details like dress code & cover charges need confirmation.",
    },



]